version: '3.5'

services:
  # Data storage
  mongodb:
    extends:
      file: ../common/mongo.yml
      service: mongodb
    env_file: local.env
    ports:
      - "27017:27017"
    volumes:
      - "./run/data/mongodb:/mongodb_data"
  # Event bus
  kafka:
    extends:
      file: ../common/kafka.yml
      service: kafka
    volumes:
      - "./run/data/kafka:/kafka_data"
  # Data processing
  spark:
    extends:
      file: ../common/apache-spark.yml
      service: spark
  # Development
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 18082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CLUSTERS_0_NAME: local
